name: Master test
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
      - test
  pull_request:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          rake pods
          rake mock
          swift test
          fastlane ios test
      - run: echo "This job's status is ${{ job.status }}."
