name: Master test
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
      - test
  pull_request:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-latest
    steps:
      - run: echo "1. The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "2. This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "3. The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "4. The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "5. The workflow is now ready to test your code on the runner:"
      - name: Run tests
        run: |
          swift test
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'test'
      - run: echo "This job's status is ${{ job.status }}."
