name: Master test
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
      - test
  pull_request:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.4.0'
      - run: xcode-select -p
      - name: Prepare for tests
        run: |
          rake pods
          rake mock
      - name: Run tests iOS
        run: |
          xcodebuild clean test  -workspace ./SwiftyMocky.xcworkspace -scheme Mocky_Tests_iOS -destination "platform=iOS Simulator,name=iPhone 11 Pro"
      - name: Run tests SwiftPM
        run: |
          swift test
      - run: echo "This job's status is ${{ job.status }}."
